apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ddclient.fullname" . }}
  labels:
    {{- include "ddclient.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "ddclient.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ddclient.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
#          command: ['sh', '-c', 'cat /etc/ddclient/ddclient.conf && sleep 3600']
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: 
          {{- range $arg := .Values.image.args }}
            - {{ $arg }}
          {{- end }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
