apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.certificate.name }}
  labels:
    {{- include "static-site.labels" . | nindent 4 }}
spec:
  secretName: {{ .Values.certificate.name }}
  issuerRef:
    name: {{ include "static-site.fullname" . }}
    kind: ClusterIssuer
  dnsNames:
  - {{ .Values.certificate.dnsName }}
