apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name }}
  namespace: {{ .Release.Namespace | quote }}
  labels: 
    {{- include "static-site.labels" . | nindent 4 }}
data:
{{ (.Files.Glob "files/httpd.conf").AsConfig | indent 2 }}

