# Default values for qapps.
issuer:
  email: martinjcolley@gmail.com
  server: https://acme-v02.api.letsencrypt.org/directory
certificate:
  name: musings-cert
  dnsName: musings.thruhere.net
replicaCount: 2
volumes:
    - name: content-from-git
      emptyDir: {}
    - name: config-volume
      configMap:
        name: httpd-conf
gitsyncimage:
  repository: registry.k8s.io/git-sync/git-sync
  pullPolicy: IfNotPresent
  tag: "v4.1.0"
  args:
    - --repo=https://github.com/MoTTTT/musings.git
    - --depth=1
    - --period=240s
    - --max-failures=10
    - --link=current
    - --root=/git-apache
    - --verbose=9
  volumeMounts:
  - name: content-from-git
    mountPath: /git-apache
apacheimage:
  repository: httpd
  pullPolicy: IfNotPresent
  tag: "alpine"
  volumeMounts:
    - name: content-from-git
      mountPath: /usr/local/apache2/htdocs/
      readOnly: true
    - name: config-volume
      mountPath: /usr/local/apache2/conf/httpd.conf
      subPath: httpd.conf
configmap:
  name: httpd-conf
serviceAccount:
  create: false
  automount: true
  annotations: {}
  name: ""
podAnnotations: {} 
podLabels: {}
podSecurityContext:
  fsGroup: 101
securityContext: {}
service:
  type: ClusterIP
  port: 80
  targetport: 80
ingress:
  enabled: true
  className: "nginx"
  hosts:
  - host: musings.thruhere.net
    paths:
      - path: /
        pathType: ImplementationSpecific
  tls:
    - secretName: musings-cert
      hosts:
        - musings.thruhere.net
test:
  url: "https://musings.thruhere.net/index.html"
resources: {}
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 20
nodeSelector: {}
tolerations: []
affinity: {}
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
